# Generated by Django 3.2.2 on 2021-06-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('0', 'select'), ('1', 'Computer Science and Engineering'), ('2', 'Biosciences and Bioengineering'), ('3', 'Chemical Engineering'), ('4', 'Civil Engineering'), ('5', 'Chemistry'), ('7', 'Design'), ('8', 'Electronics and Electrical Engineering'), ('9', 'Mechanical Engineering'), ('10', 'Electronics and Communications Engineering'), ('11', 'Mathematics and Computing'), ('12', 'Engineering Physics'), ('13', 'Humanities and Social Sciences')], default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.CharField(choices=[('0', 'select'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], default='0', max_length=3),
        ),
    ]
