# Generated by Django 3.2.2 on 2021-06-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210629_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roll',
            field=models.IntegerField(default=0),
        ),
    ]
