# Generated by Django 3.2.2 on 2021-07-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.CharField(choices=[('0', 'select'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17')], default='0', max_length=13),
        ),
    ]
