# Generated by Django 3.2.4 on 2021-07-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210712_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batch',
            field=models.CharField(choices=[('2001', 'B.Tech 20'), ('1901', 'B.Tech 19'), ('1801', 'B.Tech 18'), ('1701', 'B.Tech 17'), ('1601', 'B.Tech 16'), ('2002', 'B.Des 20'), ('1902', 'B.Des 19'), ('1802', 'B.Des 18'), ('1702', 'B.Des 17'), ('1602', 'B.Des 16'), ('2041', 'M.Tech 20'), ('1941', 'M.Tech 19'), ('1841', 'M.Tech 18'), ('1741', 'M.Tech 17'), ('1641', 'M.Tech 16'), ('2061', 'PhD 20'), ('1961', 'PhD 19'), ('1861', 'PhD 18'), ('1761', 'PhD 17'), ('1661', 'PhD 16')], default='{{us', max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('01', 'Computer Science and Engineering'), ('02', 'Electronics and Communications Engineering'), ('03', 'Mechanical Engineering'), ('04', 'Chemical Engineering'), ('05', 'Design'), ('06', 'Biosciences and Bioengineering'), ('07', 'Civil Engineering'), ('08', 'Electronics and Electrical Engineering'), ('21', 'Engineering Physics'), ('22', 'Chemimal Science and Technology'), ('23', 'Mathematics and Computing'), ('', 'Humanities and Social Sciences')], default='er', max_length=50),
        ),
    ]
