# Generated by Django 3.2.4 on 2021-07-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210712_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batch',
            field=models.CharField(default='0', max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll',
            field=models.CharField(default='0', max_length=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
