# Generated by Django 3.2.4 on 2021-07-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210712_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='semester',
        ),
    ]
