# Generated by Django 3.2.4 on 2021-07-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='programme',
            field=models.CharField(default='0', max_length=13),
        ),
    ]
