# Generated by Django 3.2.9 on 2022-02-12 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20220121_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(choices=[('0', 'Select'), ('SWC', 'SWC'), ('CODING CLUB', 'CODING CLUB'), ('AERO CLUB', 'AERO CLUB'), ('ASTRO CLUB', 'ASTRO CLUB'), ('CA CLUB', 'CA CLUB'), ('EE CLUB', 'EE CLUB'), ('PRAKRITI CLUB', 'PRAKRITI CLUB'), ('FNC CLUB', 'FNC CLUB'), ('ROBOTICS CLUB', 'ROBOTICS CLUB'), ('ED CLUB', 'ED CLUB'), ('UG CLUB', 'UG CLUB'), ('ALCHER CLUB', 'ALCHER CLUB'), ('TECHNICHE CLUB', 'TECHNICHE CLUB'), ('SAIL CLUB', 'SAIL CLUB'), ('AI CLUB', 'AI CLUB'), ('CCD CLUB', 'CCD CLUB'), ('OTHER CLUB', 'OTHER CLUB')], max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('date', models.DateField(default=datetime.date(2022, 2, 12))),
                ('deadline', models.DateField(blank=True, default=datetime.date(2022, 2, 12), null=True)),
                ('time_from', models.TimeField(default=datetime.time(10, 15, 28, 470860))),
                ('time_to', models.TimeField(default=datetime.time(10, 15, 28, 470860))),
                ('remainder', models.CharField(choices=[('0', 'Select'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Week before', 'Week before'), ('Custom', 'Custom')], default='None', max_length=12)),
                ('remainder_date', models.DateField(blank=True, default=datetime.date(2022, 2, 12), help_text='add date only if remainder type is custom', null=True)),
                ('remainder_time', models.TimeField(default=datetime.time(10, 15, 28, 471862))),
                ('guests', models.JSONField(blank=True, default=list, null=True)),
                ('location', models.JSONField(blank=True, default=dict, null=True)),
                ('announcement', models.JSONField(blank=True, default=dict, null=True)),
                ('resources_upload', models.FileField(blank=True, null=True, upload_to='media/resources')),
                ('drive_links', models.JSONField(blank=True, default=list, null=True)),
                ('payment', models.JSONField(blank=True, default=dict, null=True)),
                ('emails', models.JSONField(blank=True, default=dict, null=True)),
                ('page_view', models.JSONField(blank=True, default=dict, null=True)),
                ('feedback', models.JSONField(blank=True, default=dict, null=True)),
                ('host', models.ManyToManyField(blank=True, null=True, related_name='event_host', to='users.Profile')),
                ('rsvp_users', models.ManyToManyField(blank=True, null=True, related_name='rsvp_tasks', to='users.Profile')),
                ('speaker', models.ManyToManyField(blank=True, null=True, related_name='event_speaker', to='users.Profile')),
            ],
        ),
    ]
