# Generated by Django 3.2.2 on 2021-06-29 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='time_from',
        ),
        migrations.AddField(
            model_name='task',
            name='time_to',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
