# Generated by Django 3.1.2 on 2022-01-04 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_task',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 12, 10, 36, 581051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 12, 10, 36, 691059, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 12, 10, 36, 691059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 4, 12, 10, 36, 691059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2022, 1, 4, 12, 10, 36, 691059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2022, 1, 4, 12, 10, 36, 691059, tzinfo=utc)),
        ),
    ]
