# Generated by Django 3.2.9 on 2022-01-21 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_id'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_task',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 21)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 21), null=True),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='remainder_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 21), help_text='add date only if remainder type is custom', null=True),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='remainder_time',
            field=models.TimeField(default=datetime.time(15, 11, 39, 593481)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='rsvp_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='rsvp_tasks', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='time_from',
            field=models.TimeField(default=datetime.time(15, 11, 39, 593481)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='time_to',
            field=models.TimeField(default=datetime.time(15, 11, 39, 593481)),
        ),
    ]
