# Generated by Django 3.2.2 on 2021-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210629_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='event_category',
            field=models.CharField(choices=[('0', 'select'), ('Academic Activities', 'Academic Activities'), ('Club Related Activities', 'Club Related Activities'), ('Organisation Related Activities', 'Organisation Related Activities'), ('Seasonal Activities', 'Seasonal Activities'), ('Personal Tasks', 'Personal Tasks'), ('Other Activities', 'Other Activities')], default='0', max_length=40),
        ),
    ]
