# Generated by Django 3.2.2 on 2021-07-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210701_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='event_category',
        ),
        migrations.AddField(
            model_name='task',
            name='event_type',
            field=models.CharField(choices=[('0', 'select'), ('Academic Activities', 'Academic Activities'), ('Branch related Activities', 'Branch related Activities'), ('Club Related Activities', 'Club Related Activities'), ('Organisation Related Activities', 'Organisation Related Activities'), ('Seasonal Activities', 'Seasonal Activities'), ('Personal Tasks', 'Personal Tasks'), ('Other Activities', 'Other Activities')], default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='target_branch',
            field=models.CharField(choices=[('0', 'self'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='0', max_length=45),
        ),
    ]
