# Generated by Django 3.2.11 on 2022-01-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220121_1511'),
        ('tasks', '0004_auto_20220121_1333'),
    ]

    operations = [
    ]
