# Generated by Django 3.2.9 on 2022-01-21 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_merge_0002_auto_20220121_1511_0004_auto_20220121_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_task',
            name='remainder_time',
            field=models.TimeField(default=datetime.time(16, 32, 47, 730854)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='time_from',
            field=models.TimeField(default=datetime.time(16, 32, 47, 730854)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='time_to',
            field=models.TimeField(default=datetime.time(16, 32, 47, 730854)),
        ),
    ]
