# Generated by Django 3.2.3 on 2022-01-26 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20220121_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_task',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 26)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 26), null=True),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='remainder_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 26), help_text='add date only if remainder type is custom', null=True),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='remainder_time',
            field=models.TimeField(default=datetime.time(21, 33, 36, 521071)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='time_from',
            field=models.TimeField(default=datetime.time(21, 33, 36, 521071)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='time_to',
            field=models.TimeField(default=datetime.time(21, 33, 36, 521071)),
        ),
    ]
