# Generated by Django 3.2.4 on 2021-07-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210712_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='target_batch',
            field=models.CharField(choices=[('0', 'self'), ('All Batches', 'All Batches'), ('Whole B.Tech', 'Whole B.Tech'), ('Whole B.Des', 'Whole B.Des'), ('Whole M.Tech', 'Whole M.Tech'), ('Whole PhD', 'Whole PhD'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='0', max_length=13),
        ),
    ]
