# Generated by Django 3.2.3 on 2022-01-27 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20220126_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_task',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 27)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 27), null=True),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='remainder_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 27), help_text='add date only if remainder type is custom', null=True),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='remainder_time',
            field=models.TimeField(default=datetime.time(10, 31, 38, 162393)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='time_from',
            field=models.TimeField(default=datetime.time(10, 31, 38, 162393)),
        ),
        migrations.AlterField(
            model_name='my_task',
            name='time_to',
            field=models.TimeField(default=datetime.time(10, 31, 38, 162393)),
        ),
    ]
