# Generated by Django 3.2.4 on 2021-07-15 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20210715_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_event',
            field=models.CharField(choices=[('0', 'None'), ('Assignments', 'Assignments'), ('Quizzes', 'Quizzes'), ('Exam', 'Exam'), ('Viva', 'Viva'), ('Lab Report', 'Lab Report')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 15, 9, 4, 38, 989588, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='event_type',
            field=models.CharField(choices=[('0', 'Academic Activities')], default='Academic Activities', max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 15, 9, 4, 39, 45471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 9, 4, 39, 45471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 9, 4, 39, 45471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 9, 4, 39, 45471, tzinfo=utc)),
        ),
    ]
