# Generated by Django 3.2.4 on 2021-07-15 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20210715_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 15, 9, 6, 22, 103764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 15, 9, 6, 22, 155625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 9, 6, 22, 155625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='sub_event',
            field=models.CharField(choices=[('0', 'Select'), ('Assignments', 'Assignments'), ('Quizzes', 'Quizzes'), ('Exam', 'Exam'), ('Viva', 'Viva'), ('Lab Report', 'Lab Report')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 9, 6, 22, 155625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 9, 6, 22, 155625, tzinfo=utc)),
        ),
    ]
