# Generated by Django 3.2.4 on 2021-07-15 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_auto_20210715_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='course_name',
            field=models.CharField(choices=[('0', 'Select'), ('BT101', 'BT101'), ('BT201', 'BT201'), ('BT202', 'BT202'), ('BT203', 'BT203'), ('BT204', 'BT204'), ('BT205', 'BT205'), ('BT206', 'BT206'), ('BT207', 'BT207'), ('BT208', 'BT208'), ('BT209', 'BT209'), ('BT211', 'BT211'), ('BT301', 'BT301'), ('BT302', 'BT302'), ('BT303', 'BT303'), ('BT304', 'BT304'), ('BT305', 'BT305'), ('BT306', 'BT306'), ('BT307', 'BT307'), ('BT308', 'BT308'), ('BT311', 'BT311'), ('BT312', 'BT312'), ('BT3xx', 'BT3xx'), ('BT401', 'BT401'), ('BT402', 'BT402'), ('CH101', 'CH101'), ('CH110', 'CH110'), ('CH211', 'CH211'), ('CH212', 'CH212'), ('CH221', 'CH221'), ('CH222', 'CH222'), ('CH2xx', 'CH2xx'), ('CH231', 'CH231'), ('CH223', 'CH223'), ('CH233', 'CH233'), ('CH301', 'CH301'), ('CH302', 'CH302'), ('CH314', 'CH314'), ('CH316', 'CH316'), ('CH323', 'CH323'), ('CH331', 'CH331'), ('CH332', 'CH332'), ('CH334', 'CH334'), ('CH335', 'CH335'), ('CH401', 'CH401'), ('CH498', 'CH498'), ('CH499', 'CH499'), ('CH4xx', 'CH4xx'), ('CH4xxx', 'CH4xxx'), ('CL101', 'CL101'), ('CL201', 'CL201'), ('CL202', 'CL202'), ('CL203', 'CL203'), ('CL204', 'CL204'), ('CL205', 'CL205'), ('CL206', 'CL206'), ('CL207', 'CL207'), ('CL208', 'CL208'), ('CL209', 'CL209'), ('CL210H', 'CL210H'), ('CL211H', 'CL211H'), ('CL301', 'CL301'), ('CL302', 'CL302'), ('CL303', 'CL303'), ('CL304', 'CL304'), ('CL305', 'CL305'), ('CL306', 'CL306'), ('CL310', 'CL310'), ('CL311', 'CL311'), ('CL312', 'CL312'), ('CL313', 'CL313'), ('CL314H', 'CL314H'), ('CL315H', 'CL315H'), ('CL3xx', 'CL3xx'), ('CLxxx', 'CLxxx'), ('CL4xx', 'CL4xx'), ('CE201', 'CE201'), ('CE202', 'CE202'), ('CE203', 'CE203'), ('CE205', 'CE205'), ('CE206', 'CE206'), ('CE207', 'CE207'), ('CE208', 'CE208'), ('CE211', 'CE211'), ('CE212', 'CE212'), ('CE213', 'CE213'), ('CE214', 'CE214'), ('CE215', 'CE215'), ('CE220', 'CE220'), ('CE221', 'CE221'), ('CE222', 'CE222'), ('CE223', 'CE223'), ('CE302', 'CE302'), ('CE303', 'CE303'), ('CE304', 'CE304'), ('CE305', 'CE305'), ('CE308', 'CE308'), ('CE309', 'CE309'), ('CE313', 'CE313'), ('CE314', 'CE314'), ('CE316', 'CE316'), ('CE320', 'CE320'), ('CE321', 'CE321'), ('CE322', 'CE322'), ('CE323', 'CE323'), ('CE324', 'CE324'), ('CE402', 'CE402'), ('CE498', 'CE498'), ('CE499', 'CE499'), ('CExxx', 'CExxx'), ('CE4xx', 'CE4xx'), ('CS101', 'CS110'), ('CS110', 'CS110'), ('CS201', 'CS201'), ('CS203', 'CS203'), ('CS204', 'CS204'), ('CS205', 'CS205'), ('CS207', 'CS207'), ('CS221', 'CS221'), ('CS223', 'CS223'), ('CS224', 'CS224'), ('CS242', 'CS242'), ('CS245', 'CS245'), ('CS246', 'CS246'), ('CS341', 'CS341'), ('CS342', 'CS342'), ('CS343', 'CS343'), ('CS344', 'CS344'), ('CS345', 'CS345'), ('CS346', 'CS346'), ('CS348', 'CS348'), ('CSxxx', 'CSxxx'), ('CS498', 'CS498'), ('CS499', 'CS499'), ('CSxxx', 'CSxxx'), ('CS4xx', 'CS4xx'), ('DD101', 'DD101'), ('DD102', 'DD102'), ('DD103', 'DD103'), ('DD104', 'DD104'), ('DD105', 'DD105'), ('DD111', 'DD111'), ('DD112', 'DD112'), ('DD113', 'DD113'), ('DD201', 'DD201'), ('DD202', 'DD202'), ('DD203', 'DD201'), ('DD203', 'DD203'), ('DD204', 'DD204'), ('DD205', 'DD205'), ('DD206', 'DD206'), ('DD212', 'DD212'), ('DD213', 'DD213'), ('DD214', 'DD214'), ('DD215', 'DD215'), ('DD216', 'DD216'), ('DD301', 'DD301'), ('DD302', 'DD302'), ('DD303', 'DD301'), ('DD303', 'DD303'), ('DD304', 'DD304'), ('DD311', 'DD311'), ('DD312', 'DD312'), ('DD3xX', 'DD3xx'), ('DD398', 'DD398'), ('DD401', 'DD401'), ('DD402', 'DD402'), ('DD411', 'DD411'), ('DD498', 'DD498'), ('DD499', 'DD499'), ('DDxxx', 'DDxxx'), ('DD4xx', 'DD4xx'), ('EE101', 'EE101'), ('EE102', 'EE102'), ('EE203', 'EE203'), ('EE204', 'EE204'), ('EE205', 'EE205'), ('EE206', 'EE206'), ('EE207', 'EE207'), ('EE210', 'EE210'), ('EE211', 'EE211'), ('EE220', 'EE220'), ('EE230', 'EE230'), ('EE250', 'EE250'), ('EE252', 'EE252'), ('EE253', 'EE253'), ('EE312', 'EE312'), ('EE313', 'EE313'), ('EE321', 'EE321'), ('EE331', 'EE331'), ('EE332', 'EE332'), ('EE333', 'EE333'), ('EE334', 'EE334'), ('EE340', 'EE340'), ('EE351', 'EE351'), ('EE360', 'EE360'), ('EE370', 'EE370'), ('EE371', 'EE371'), ('EE380', 'EE380'), ('EE381', 'EE381'), ('EE390', 'EE390'), ('EE396', 'EE396'), ('EE398', 'EE398'), ('EE399', 'EE399'), ('EE3xx', 'EE3xx'), ('EE498', 'EE498'), ('EE499', 'EE499'), ('EExxx', 'EExxx'), ('EE4xx', 'EE4xx'), ('MA101', 'MA101'), ('MA102', 'MA102'), ('MA201', 'MA201'), ('MA221', 'MA221'), ('MA222', 'MA222'), ('MA224', 'MA224'), ('MA225', 'MA225'), ('MA251', 'MA251'), ('MA252', 'MA252'), ('MA250', 'MA250'), ('MA252', 'MA252'), ('MA271', 'MA271'), ('MA321', 'MA321'), ('MA322', 'MA322'), ('MA323', 'MA323'), ('MA324', 'MA324'), ('MA351', 'MA351'), ('MA372', 'MA372'), ('MA373', 'MA373'), ('MA374', 'MA374'), ('MA3xx', 'MA3xx'), ('MA423', 'MA423'), ('MA473', 'MA473'), ('MA498', 'MA498'), ('MA499', 'MA499'), ('MAxxx', 'MAxxx'), ('MA4xx', 'MA4xx'), ('ME101', 'ME100'), ('ME110', 'ME110'), ('ME211', 'ME211'), ('ME212', 'ME212'), ('ME213', 'ME213'), ('ME214', 'ME214'), ('ME215', 'ME215'), ('ME216', 'ME216'), ('ME221', 'ME221'), ('ME222', 'ME222'), ('ME223', 'ME223'), ('ME224', 'ME224'), ('ME225', 'ME225'), ('ME226', 'ME226'), ('ME311', 'ME311'), ('ME312', 'ME312'), ('ME313', 'ME313'), ('ME314', 'ME314'), ('ME315', 'ME315'), ('ME321', 'ME321'), ('ME322', 'ME322'), ('ME323', 'ME323'), ('ME324', 'ME324'), ('ME325', 'ME325'), ('ME326', 'ME326'), ('ME398', 'ME398'), ('ME399', 'ME399'), ('ME3xx', 'ME3xx'), ('ME401', 'ME401'), ('ME498', 'ME498'), ('ME499', 'ME499'), ('MExxx', 'MExxx'), ('ME4xx', 'ME4xx'), ('PH101', 'PH101'), ('PH102', 'PH102'), ('PH110', 'PH110'), ('PH201', 'PH201'), ('PH202', 'PH202'), ('PH203', 'PH201'), ('PH203', 'PH203'), ('PH204', 'PH204'), ('PH205', 'PH205'), ('PH206', 'PH206'), ('PH207', 'PH207'), ('PH208', 'PH208'), ('PH209', 'PH209'), ('PH210', 'PH210'), ('PH211', 'PH211'), ('PH301', 'PH301'), ('PH302', 'PH302'), ('PH303', 'PH301'), ('PH303', 'PH303'), ('PH304', 'PH304'), ('PH305', 'PH305'), ('PH306', 'PH306'), ('PH307', 'PH307'), ('PH308', 'PH308'), ('PH309', 'PH309'), ('PH310', 'PH310'), ('PH312', 'PH312'), ('PH411', 'PH411'), ('PH413', 'PH413'), ('PH415', 'PH415'), ('PH421', 'PH421'), ('PH422', 'PH422'), ('PHxxx', 'PHxxx'), ('PH4xx', 'PH4xx')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 15, 12, 9, 40, 70841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 15, 12, 9, 40, 124697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 12, 9, 40, 124697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 12, 9, 40, 124697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 12, 9, 40, 124697, tzinfo=utc)),
        ),
    ]
