# Generated by Django 3.2.4 on 2021-07-16 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0056_auto_20210716_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeroclub',
            name='club',
            field=models.CharField(choices=[('0', 'AERO-MODELLING CLUB')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='club',
            field=models.CharField(choices=[('0', 'Alcheringa')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 393733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 394733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 394733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 394733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 394733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 394733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='club',
            field=models.CharField(choices=[('0', 'Astronomy CLUB')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 387748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 387748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 387748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 387748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 387748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 387748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='bt',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='bt',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='club',
            field=models.CharField(choices=[('0', 'Consulting and Analytics Club')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 388746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 388746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 388746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 388746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 388746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 388746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 371791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 371791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 371791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 371791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='ce',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='ce',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 371791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 371791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 370796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='ch',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='ch',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 369797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 370796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 370796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 370796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 370796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='cl',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='cl',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 370796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 370796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='club',
            field=models.CharField(choices=[('0', 'CODING CLUB')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 386753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='cse',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='cse',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='des',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='des',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 372788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 373788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 373788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 373788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 373788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='ece',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='ece',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 373788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 373788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='club',
            field=models.CharField(choices=[('0', 'Entrepreneurial Development Cell')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 392738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 392738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 392738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 392738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 392738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 392738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='club',
            field=models.CharField(choices=[('0', 'Electronics Club')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 388746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 389740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 389740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 389740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 389740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 389740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 374784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 374784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 374784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 374784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='eee',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='eee',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 374784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 374784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='club',
            field=models.CharField(choices=[('0', 'Finance and Economics club')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 390740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 390740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 390740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 390740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 390740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 390740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 375783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 375783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 375783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 375783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='ma',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='ma',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 375783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 375783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 376780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 376780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 376780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 376780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='me',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='me',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 376780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 376780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 377774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 377774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 377774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 377774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='ph',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='ph',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 377774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 377774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='club',
            field=models.CharField(choices=[('0', 'Prakriti Club')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 389740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 389740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 389740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 390740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 389740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 389740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='club',
            field=models.CharField(choices=[('0', 'Robotics Club')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 391738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 391738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 391738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 391738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 391738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 391738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='club',
            field=models.CharField(choices=[('0', 'Students Web Committee')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='swc',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 378780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 378780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 378780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 378780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='swc',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='swc',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 378780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 378780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 290009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 368801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 368801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 368801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 368801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 368801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='club',
            field=models.CharField(choices=[('0', 'Udgam - IITG Entrepreneurship Summit')], default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 393733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 393733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 393733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 393733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='target_batch',
            field=models.CharField(choices=[('0', 'Select'), ('All Batches', 'All Batches'), ('B.Tech', 'B.Tech'), ('B.Tech 20', 'B.Tech 20'), ('B.Tech 19', 'B.Tech 19'), ('B.Tech 18', 'B.Tech 18'), ('B.Tech 17', 'B.Tech 17'), ('B.Tech 16', 'B.Tech 16'), ('B.Des', 'B.Des'), ('B.Des 20', 'B.Des 20'), ('B.Des 19', 'B.Des 19'), ('B.Des 18', 'B.Des 18'), ('B.Des 17', 'B.Des 17'), ('B.Des 16', 'B.Des 16'), ('M.Tech', 'M.Tech'), ('M.Tech 20', 'M.Tech 20'), ('M.Tech 19', 'M.Tech 19'), ('M.Tech 18', 'M.Tech 18'), ('M.Tech 17', 'M.Tech 17'), ('M.Tech 16', 'M.Tech 16'), ('PhD', 'PhD'), ('PhD 20', 'PhD 20'), ('PhD 19', 'PhD 19'), ('PhD 18', 'PhD 18'), ('PhD 17', 'PhD 17'), ('PhD 16', 'PhD 16')], default='Self', max_length=13),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='target_branch',
            field=models.CharField(choices=[('0', 'Select'), ('All Branches', 'All Branches'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Engineering Physics', 'Engineering Physics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences')], default='Self', max_length=45),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 393733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 6, 36, 5, 393733, tzinfo=utc)),
        ),
    ]
