# Generated by Django 3.1.2 on 2021-10-18 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0069_auto_20211004_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='announcements',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 664841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 664841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 665841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 665841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 665841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 665841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 685400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 685400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 685400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 685400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 685400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 685400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 678399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 678399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 678399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 679402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 678399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 678399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 666842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 666842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 666842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 666842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 666842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 666842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 648841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 648841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 648841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 648841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 648841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 648841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 667843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 667843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 667843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 667843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 667843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 667843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 686400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 686400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 686400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 686400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 686400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 686400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 652840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 652840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ce',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 652840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 652840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 652840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 652840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 649843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 649843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ch',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 650840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 650840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 650840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 650840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 651840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 651840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cl',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 651840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 651840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 651840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 651840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 663841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 663841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 664841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 664841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 663841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 664841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 653840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 653840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cse',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 653840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 653840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 653840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 653840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 654840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 654840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='des',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 654840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 654840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 654840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 654840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 655840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 656840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ece',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 656840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 656840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 656840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 656840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 674156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 674156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 674156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 674842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 674156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 674156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 668843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 668843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 668843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 668843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 668843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 668843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 657840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 657840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eee',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 657840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 658842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 657840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 657840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 671842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 671842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 671842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 671842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 671842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 671842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 659843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 659843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ma',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 659843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 659843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 659843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 659843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 660841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 660841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='me',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 660841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 660841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 660841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 660841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 682400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 682400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 682400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 682400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 682400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 682400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 661841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 661841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ph',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 661841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 661841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 661841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 661841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 669845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 669845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 670842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 670842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 670842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 670842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 672842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 672842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 672842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 672842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 672842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 672842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 683398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 683398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 683398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 683398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 683398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 683398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 662841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 662841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='swc',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 662841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 663841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 662841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 662841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 489807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 647840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 647840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 647840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 647840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 647840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 680400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 680400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 680400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 680400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 680400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 680400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 675843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 675843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 676847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 676847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 675843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 11, 1, 676847, tzinfo=utc)),
        ),
    ]
