# Generated by Django 3.1.2 on 2021-10-18 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0071_auto_20211019_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='aeroclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='aeroclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='aiclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='aiclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='aiclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='alcherclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='alcherclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='alcherclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='astroclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='astroclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='astroclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='bt',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='bt',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bt',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='caclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='caclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='caclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ccdclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='ccdclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ccdclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ce',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='ce',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ce',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ch',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='ch',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ch',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cl',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='cl',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cl',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='codingclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='codingclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='codingclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cse',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='cse',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cse',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='des',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='des',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='des',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ece',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='ece',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ece',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='edclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='edclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='edclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='eeclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='eeclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='eeclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='eee',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='eee',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='eee',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='fncclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='fncclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fncclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ma',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='ma',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ma',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='me',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='me',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='otherclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='otherclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='otherclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ph',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='ph',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ph',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='prakriticlub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='prakriticlub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='prakriticlub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='roboticsclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='roboticsclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='roboticsclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='sailclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='sailclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sailclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='swc',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='swc',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='swc',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='task',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='technicheclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='technicheclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='technicheclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ugclub',
            name='announcements',
            field=models.TextField(blank=True, default='', help_text='announcements should be seperated by comma, so that we can list them as points', null=True),
        ),
        migrations.AddField(
            model_name='ugclub',
            name='notifications',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ugclub',
            name='resources_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 739025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 739025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 739025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 739025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 739025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aeroclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 739025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 758026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 758026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 758026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 758026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 758026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aiclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 758026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 751026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 751026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 751026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 751026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 751026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alcherclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 751026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 740025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 740025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 741026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 741026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 741026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='astroclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 741026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 717023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 718023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 718023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 718023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 718023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bt',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 718023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 742025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 742025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 742025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 742025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 742025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 742025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 759026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 759026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 759026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 759026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 759026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ccdclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 759026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 722024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 722024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 722024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 722024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 722024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ce',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 722024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 719023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 719023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 719023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 719023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 719023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ch',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 719023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 720024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 720024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 721026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 721026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 720024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cl',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 720024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 738022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 738022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 738022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 738022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 738022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codingclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 738022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 724022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 724022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 725022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 725022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 724022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cse',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 725022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 727022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 727022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 727022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 727022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 727022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='des',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 727022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 729022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 729022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 729022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 729022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 729022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ece',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 729022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 748025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 748025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 748025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 748025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 748025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 748025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 743026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 743026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 743026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 743026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 743026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eeclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 743026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 730022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 730022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 731023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 731023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 731023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eee',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 731023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 745025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 746025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 746025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 746025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 746025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fncclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 746025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 732023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 732023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 732023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 732023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 732023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ma',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 732023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 733022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 733022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 733022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 734022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 733022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='me',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 733022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 755026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 755026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 755026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 755026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 755026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 755026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 735023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 735023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 735023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 735023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 735023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 735023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 744025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 744025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 744025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 744025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 744025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prakriticlub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 744025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 747029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 747029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 747029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 747029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 747029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roboticsclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 747029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 756026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 756026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 757026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 757026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 756026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sailclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 756026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 736022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 736022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 736022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 736022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 736022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swc',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 736022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 557987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 716023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 716023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 716023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 716023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 716023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 753023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 753023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 753023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 753023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 753023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='technicheclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 753023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 749025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 749025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='remainder_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 750026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='remainder_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 750026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 750026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ugclub',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 20, 32, 40, 750026, tzinfo=utc)),
        ),
    ]
