from django.contrib import admin
from users import models

# Register your models here.
admin.site.register(models.Profile)
admin.site.register(models.Rsvp_AEROCLUB)
admin.site.register(models.Rsvp_AICLUB)
admin.site.register(models.Rsvp_ALCHERCLUB)
admin.site.register(models.Rsvp_ASTROCLUB)
admin.site.register(models.Rsvp_BT)
admin.site.register(models.Rsvp_CACLUB)
admin.site.register(models.Rsvp_CCDCLUB)
admin.site.register(models.Rsvp_CE)
admin.site.register(models.Rsvp_CH)
admin.site.register(models.Rsvp_CL)
admin.site.register(models.Rsvp_CODINGCLUB)
admin.site.register(models.Rsvp_CSE)
admin.site.register(models.Rsvp_DES)
admin.site.register(models.Rsvp_ECE)
admin.site.register(models.Rsvp_EDCLUB)
admin.site.register(models.Rsvp_EECLUB)
admin.site.register(models.Rsvp_EEE)
admin.site.register(models.Rsvp_FNCCLUB)
admin.site.register(models.Rsvp_MA)
admin.site.register(models.Rsvp_ME)
admin.site.register(models.Rsvp_OTHERCLUB)
admin.site.register(models.Rsvp_PH)
admin.site.register(models.Rsvp_PRAKRITICLUB)
admin.site.register(models.Rsvp_ROBOTICSCLUB)
admin.site.register(models.Rsvp_SAILCLUB)
admin.site.register(models.Rsvp_SWC)
admin.site.register(models.Rsvp_Task)
admin.site.register(models.Rsvp_TechnicheCLUB)
admin.site.register(models.Rsvp_UGCLUB)