# Generated by Django 3.2.3 on 2022-03-08 02:28

import club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(choices=[('0', 'Select'), ('SWC', 'SWC'), ('CODING CLUB', 'CODING CLUB'), ('AERO CLUB', 'AERO CLUB'), ('ASTRO CLUB', 'ASTRO CLUB'), ('CA CLUB', 'CA CLUB'), ('EE CLUB', 'EE CLUB'), ('PRAKRITI CLUB', 'PRAKRITI CLUB'), ('FNC CLUB', 'FNC CLUB'), ('ROBOTICS CLUB', 'ROBOTICS CLUB'), ('ED CLUB', 'ED CLUB'), ('UG CLUB', 'UG CLUB'), ('ALCHER CLUB', 'ALCHER CLUB'), ('TECHNICHE CLUB', 'TECHNICHE CLUB'), ('SAIL CLUB', 'SAIL CLUB'), ('AI CLUB', 'AI CLUB'), ('CCD CLUB', 'CCD CLUB'), ('OTHER CLUB', 'OTHER CLUB')], max_length=20)),
                ('title', models.CharField(default=False, max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=club.models.event_image_path)),
            ],
        ),
    ]
